services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: TareaEFJ       
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - TareaEFJ_data:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d TareaEFJ"]  
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .                      
      dockerfile: Api/Api.Dockerfile  
    environment:
      ASPNETCORE_HTTP_PORTS: "8080"    
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__Default: "Host=db;Port=5432;Database=TareaEFJ;Username=postgres;Password=postgres"  
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
volumes:
  TareaEFJ_data:  
